CREATE TABLE `journey_albums` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `route_id` int NOT NULL,
  `title` varchar(128) NOT NULL,
  `cover_photo_id` int NULL,
  `photo_count` int NOT NULL DEFAULT 0,
  `bytes_used` bigint unsigned NOT NULL DEFAULT 0,
  `status` varchar(16) NOT NULL DEFAULT 'active',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_journey_albums_user_route` (`user_id`, `route_id`),
  KEY `idx_journey_albums_user` (`user_id`),
  KEY `idx_journey_albums_route` (`route_id`),
  CONSTRAINT `journey_albums_user_id_users_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `journey_albums_route_id_travel_routes_id_fk` FOREIGN KEY (`route_id`) REFERENCES `travel_routes` (`id`) ON DELETE CASCADE
);
--> statement-breakpoint
CREATE TABLE `travel_photos` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `album_id` int NOT NULL,
  `stored_url` varchar(512) NOT NULL,
  `byte_size` int NOT NULL,
  `width` int NULL,
  `height` int NULL,
  `day_index` int NULL,
  `poi_name` varchar(128) NULL,
  `attraction_id` int NULL,
  `check_in_id` int NULL,
  `taken_at` timestamp NULL,
  `latitude` decimal(10, 7) NULL,
  `longitude` decimal(10, 7) NULL,
  `caption` varchar(512) NULL,
  `sort_order` int NOT NULL DEFAULT 0,
  `source` varchar(16) NOT NULL DEFAULT 'upload',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_travel_photos_album` (`album_id`),
  KEY `idx_travel_photos_user` (`user_id`),
  KEY `idx_travel_photos_day_poi` (`album_id`, `day_index`, `poi_name`),
  CONSTRAINT `travel_photos_user_id_users_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `travel_photos_album_id_journey_albums_id_fk` FOREIGN KEY (`album_id`) REFERENCES `journey_albums` (`id`) ON DELETE CASCADE
);
