# -*- coding: utf-8 -*-
"""第二册 发单方分册（C 端发单 · 移动端 / PC 用户端）。"""
from manual_lib import *


def build(doc):
    """构建第二册发单方分册并写入 doc。"""
    section_title(doc, '第二册')
    section_subtitle(doc, '发单方分册 · C 端发单')
    section_subtitle(doc, '移动端 / PC 用户端')
    page_break(doc)

    add_heading(doc, '第 1 章  发单方概述', level=1)
    add_para(doc, '发单方（买方）指有定制旅行需求的个人或团体用户，可在移动端或 PC 用户端发布需求、浏览服务方报价、选定报价并跟踪履约。发单方能力落点为 mobile 与 PC（C 端），B 端接单履约在 Web 商户工作台。')
    add_note(doc, '团体发单属 C 端发单方能力，落 mobile / PC；Web 商户工作台不放置纯 C 端发单方专属能力。')

    add_heading(doc, '1.1 定制服务大厅', level=2)
    add_para(doc, '定制服务大厅聚合平台已发布的可接单需求与服务商品，发单方可浏览参考、直接发单或选购现成服务商品。')
    add_image(doc, PC, '18-marketplace-hall.png', '图 1-1  PC 用户端定制服务大厅')
    add_image(doc, MOBILE, '18-marketplace-hall.png', '图 1-2  移动端定制服务大厅')
    add_heading(doc, '1.2 功能点', level=2)
    add_bullet(doc, '需求/商品卡片：封面、标题、预算区间、服务方、报价数。')
    add_bullet(doc, '分类筛选：按目的地、服务类型、预算区间筛选。')
    add_bullet(doc, '快速发单入口：顶部「发布需求」按钮直达发单表单。')
    page_break(doc)

    add_heading(doc, '第 2 章  发布需求', level=1)
    add_para(doc, '发单方填写需求表单，提交后进入需求大厅供服务方报价。支持草稿保存与多轮补充。')
    add_image(doc, PC, '19-marketplace-create.png', '图 2-1  PC 用户端发布需求')
    add_image(doc, MOBILE, '19-marketplace-create.png', '图 2-2  移动端发布需求')
    add_heading(doc, '2.1 功能点', level=2)
    add_bullet(doc, '目的地与天数：城市 + 出发/结束日期 + 人数。')
    add_bullet(doc, '预算区间：最低/最高预算，或固定预算。')
    add_bullet(doc, '主题与人群：亲子、蜜月、摄影、户外等标签。')
    add_bullet(doc, '特殊要求：自由文本补充需求细节。')
    add_bullet(doc, '草稿保存：可暂存草稿，稍后继续编辑发布。')
    add_heading(doc, '2.2 操作流程', level=2)
    add_number(doc, '在定制服务大厅点击「发布需求」。')
    add_number(doc, '填写目的地、日期、人数、预算、主题与特殊要求。')
    add_number(doc, '点击「保存草稿」暂存，或「发布」直接上架。')
    add_number(doc, '发布后可在「我的需求」查看，并接收服务方报价通知。')
    page_break(doc)

    add_heading(doc, '第 3 章  我的需求与需求详情', level=1)
    add_para(doc, '「我的需求」展示发单方发布的全部需求及状态（草稿/报价中/已选定/已关闭）。需求详情页展示需求信息、收到的报价列表与选定操作。')
    add_image(doc, PC, '20-marketplace-mine.png', '图 3-1  PC 用户端我的需求')
    add_image(doc, MOBILE, '20-marketplace-mine.png', '图 3-2  移动端我的需求')
    add_heading(doc, '3.1 功能点', level=2)
    add_bullet(doc, '需求状态：草稿、报价中、已选定报价、已关闭。')
    add_bullet(doc, '报价列表：服务方报价金额、方案摘要、服务方评分。')
    add_bullet(doc, '选定报价：选定后生成服务订单，进入履约流程。')
    add_bullet(doc, '关闭需求：可主动关闭未选定的需求。')
    add_heading(doc, '3.2 操作流程（选定报价）', level=2)
    add_number(doc, '进入「我的需求」点击需求进入详情。')
    add_number(doc, '查看收到的报价列表，对比金额与方案。')
    add_number(doc, '点击目标报价的「选定」按钮。')
    add_number(doc, '确认后生成服务订单，可在商户工作台或订单中心跟踪履约。')
    page_break(doc)

    add_heading(doc, '第 4 章  我的团体', level=1)
    add_para(doc, '团体发单支持创建团体、邀请成员、以团体名义发布需求。团体属 C 端发单方能力，落 mobile / PC。')
    add_image(doc, PC, '21-marketplace-groups.png', '图 4-1  PC 用户端我的团体')
    add_image(doc, MOBILE, '21-marketplace-groups.png', '图 4-2  移动端我的团体')
    add_image(doc, PC, '22-marketplace-group-create.png', '图 4-3  PC 用户端创建团体')
    add_image(doc, MOBILE, '22-marketplace-group-create.png', '图 4-4  移动端创建团体')
    add_heading(doc, '4.1 功能点', level=2)
    add_bullet(doc, '团体列表：展示已加入团体、角色（团长/成员）、成员数。')
    add_bullet(doc, '创建团体：填写团体名、简介、成员邀请。')
    add_bullet(doc, '团体发单：以团体名义发布需求，预算分摊。')
    add_bullet(doc, '团体详情：成员管理、团体需求、动态。')
    page_break(doc)

    add_heading(doc, '第 5 章  服务方入驻引导', level=1)
    add_para(doc, '个人用户可申请成为服务方（个人服务者认证或商户入驻），入驻审核通过后获得接单能力。完整 B 端闭环在 Web 商户工作台 /partner。')
    add_image(doc, PC, '23-marketplace-product-detail.png', '图 5-1  PC 用户端服务商品详情')
    add_heading(doc, '5.1 入驻类型', level=2)
    add_bullet(doc, '个人服务者认证：个人领队、摄影师、向导等，提交资质审核。')
    add_bullet(doc, '商户入驻：旅行社、工作室等机构，提交营业执照与团队信息。')
    add_heading(doc, '5.2 操作流程', level=2)
    add_number(doc, '在定制服务大厅或个人中心找到「服务方入驻」入口。')
    add_number(doc, '选择入驻类型（个人服务者 / 商户机构）。')
    add_number(doc, '填写资质信息并提交，等待平台审核。')
    add_number(doc, '审核通过后登录 Web 商户工作台 /partner 开始接单。')
    add_note(doc, '商户工作台完整接单、报价、履约、结算流程见第三册。')
    page_break(doc)
