# -*- coding: utf-8 -*-
"""第四册 管理员分册（B 端运营 · Web 管理端）。"""
from manual_lib import *


def build(doc):
    """构建第四册管理员分册并写入 doc。"""
    section_title(doc, '第四册')
    section_subtitle(doc, '管理员分册 · B 端运营')
    section_subtitle(doc, 'Web 管理端')
    page_break(doc)

    add_heading(doc, '第 1 章  管理端概述与登录', level=1)
    add_para(doc, 'Web 管理端（兜行管理后台）面向平台运营管理员，提供 RBAC 权限、动态侧栏、数据分析看板、运营大屏、业务/内容/发单接单/会员/系统/监控/日志全量管理。')
    add_image(doc, WEB, '01-login.png', '图 1-1  Web 管理端登录页')
    add_heading(doc, '1.1 登录流程', level=2)
    add_number(doc, '访问 http://127.0.0.1:5173/login。')
    add_number(doc, '选择「密码登录」Tab，输入 admin / admin123（演示账号）。')
    add_number(doc, '登录后进入工作台首页。')
    page_break(doc)

    add_heading(doc, '第 2 章  工作台首页', level=1)
    add_para(doc, '工作台首页展示路线、订单、打卡、待审景点等核心指标，以及站点上线状态、最新通知、更新日志、系统信息。')
    add_image(doc, WEB, '02-home-dashboard.png', '图 2-1  管理端工作台首页')
    add_heading(doc, '2.1 功能点', level=2)
    add_bullet(doc, '指标卡：路线总数、订单总数、打卡总数、待审景点数。')
    add_bullet(doc, '站点状态：一键上下线 PC/移动端/客户端，管理后台始终在线。')
    add_bullet(doc, '最新通知、更新日志、系统信息卡片。')
    page_break(doc)

    add_heading(doc, '第 3 章  数据中心', level=1)
    add_heading(doc, '3.1 数据分析看板', level=2)
    add_para(doc, '数据分析看板基于 ECharts 展示全站运营指标：用户增长、路线发布、打卡趋势、订单转化、城市分布等。')
    add_image(doc, WEB, '19-analytics.png', '图 3-1  数据分析看板')
    add_heading(doc, '3.2 旅行运营大屏', level=2)
    add_para(doc, '运营大屏 /screen/travel 全屏展示旅行运营核心指标，含地图分布、漏斗、热力图，适合投屏展示。')
    add_image(doc, SCREEN, '01-travel-cockpit.png', '图 3-2  旅行运营大屏')
    page_break(doc)

    add_heading(doc, '第 4 章  业务管理', level=1)
    add_heading(doc, '4.1 路线管理', level=2)
    add_para(doc, '路线管理列表展示全站路线，支持按关键词、状态、创建者、时间筛选与 XLSX 导出。')
    add_image(doc, WEB, '03-routes.png', '图 4-1  路线管理')
    add_heading(doc, '4.2 订单管理', level=2)
    add_image(doc, WEB, '04-orders.png', '图 4-2  订单管理')
    add_heading(doc, '4.3 打卡管理', level=2)
    add_image(doc, WEB, '05-checkins.png', '图 4-3  打卡管理')
    add_heading(doc, '4.4 打卡地图', level=2)
    add_image(doc, WEB, '06-checkins-map.png', '图 4-4  打卡地图')
    add_heading(doc, '4.5 通用表格规范', level=2)
    add_bullet(doc, '统一使用 DouxingAdminTable，列宽可拖拽调整。')
    add_bullet(doc, '空值统一显示「-」，导出 XLSX 同步占位。')
    add_bullet(doc, '筛选使用 AdminSearchBar，时间范围 value-format YYYY-MM-DD。')
    add_bullet(doc, '操作列使用 TableActionBar + TableActionButton 统一样式。')
    page_break(doc)

    add_heading(doc, '第 5 章  内容运营', level=1)
    add_heading(doc, '5.1 景点库管理', level=2)
    add_para(doc, '景点库管理维护全站景点（28 条 seed + AI 自动同步），含坐标、分类、来源、封面。')
    add_image(doc, WEB, '07-attractions-manage.png', '图 5-1  景点库管理')
    add_heading(doc, '5.2 待审景点', level=2)
    add_image(doc, WEB, '08-attractions-pending.png', '图 5-2  待审景点')
    add_heading(doc, '5.3 景点媒体审核', level=2)
    add_para(doc, 'UGC 视频/图片上传审核，POI 信任链管理。')
    add_image(doc, WEB, '09-route-media-pending.png', '图 5-3  景点媒体审核')
    add_heading(doc, '5.4 玩法动线管理', level=2)
    add_image(doc, WEB, '10-playbooks-manage.png', '图 5-4  玩法动线管理')
    page_break(doc)

    add_heading(doc, '第 6 章  发单接单监管', level=1)
    add_heading(doc, '6.1 需求监管', level=2)
    add_image(doc, WEB, '11-marketplace-demands.png', '图 6-1  需求监管')
    add_heading(doc, '6.2 纠纷处理', level=2)
    add_image(doc, WEB, '12-marketplace-disputes.png', '图 6-2  纠纷处理')
    add_heading(doc, '6.3 机构管理', level=2)
    add_image(doc, WEB, '13-marketplace-orgs.png', '图 6-3  机构管理')
    add_heading(doc, '6.4 机构入驻审核', level=2)
    add_image(doc, WEB, '14-marketplace-orgs-pending.png', '图 6-4  机构入驻审核')
    add_heading(doc, '6.5 个人服务者审核', level=2)
    add_image(doc, WEB, '15-marketplace-providers-pending.png', '图 6-5  个人服务者审核')
    page_break(doc)

    add_heading(doc, '第 7 章  会员管理', level=1)
    add_heading(doc, '7.1 会员用户', level=2)
    add_image(doc, WEB, '16-membership-users.png', '图 7-1  会员用户')
    add_heading(doc, '7.2 会员套餐', level=2)
    add_image(doc, WEB, '17-membership-products.png', '图 7-2  会员套餐')
    add_heading(doc, '7.3 会员日志', level=2)
    add_image(doc, WEB, '18-membership-logs.png', '图 7-3  会员日志')
    page_break(doc)

    add_heading(doc, '第 8 章  AI 流程编排', level=1)
    add_heading(doc, '8.1 工作流模板管理', level=2)
    add_para(doc, '可配置 DAG 工作流模板，管理 AI 规划流程节点编排。')
    add_image(doc, WEB, '20-workflow-templates.png', '图 8-1  工作流模板管理')
    page_break(doc)

    add_heading(doc, '第 9 章  系统管理', level=1)
    add_para(doc, '系统管理提供 RBAC 权限体系，含用户、角色、菜单、部门、岗位、字典、参数、公告管理。')
    add_heading(doc, '9.1 用户管理', level=2)
    add_image(doc, WEB, '21-sys-users.png', '图 9-1  用户管理')
    add_heading(doc, '9.2 角色管理', level=2)
    add_image(doc, WEB, '22-sys-roles.png', '图 9-2  角色管理')
    add_heading(doc, '9.3 菜单管理', level=2)
    add_image(doc, WEB, '23-sys-menus.png', '图 9-3  菜单管理')
    add_heading(doc, '9.4 部门管理', level=2)
    add_image(doc, WEB, '24-sys-depts.png', '图 9-4  部门管理')
    add_heading(doc, '9.5 岗位管理', level=2)
    add_image(doc, WEB, '25-sys-posts.png', '图 9-5  岗位管理')
    add_heading(doc, '9.6 字典管理', level=2)
    add_image(doc, WEB, '26-sys-dict.png', '图 9-6  字典管理')
    add_heading(doc, '9.7 系统参数', level=2)
    add_image(doc, WEB, '27-sys-config.png', '图 9-7  系统参数')
    add_heading(doc, '9.8 通知公告', level=2)
    add_image(doc, WEB, '28-sys-notices.png', '图 9-8  通知公告')
    add_heading(doc, '9.9 功能点', level=2)
    add_bullet(doc, 'RBAC：用户绑定角色，角色绑定菜单权限，requirePerm 校验。')
    add_bullet(doc, '动态菜单：菜单由后端 syncMenuSeedMetadata 同步，侧栏动态渲染。')
    add_bullet(doc, '字典：业务枚举统一字典管理，前后端共享。')
    page_break(doc)

    add_heading(doc, '第 10 章  系统监控', level=1)
    add_heading(doc, '10.1 在线用户', level=2)
    add_image(doc, WEB, '29-monitor-online.png', '图 10-1  在线用户')
    add_heading(doc, '10.2 定时任务', level=2)
    add_image(doc, WEB, '30-monitor-jobs.png', '图 10-2  定时任务')
    add_heading(doc, '10.3 数据监控', level=2)
    add_image(doc, WEB, '31-monitor-data.png', '图 10-3  数据监控')
    add_heading(doc, '10.4 服务监控', level=2)
    add_image(doc, WEB, '32-monitor-server.png', '图 10-4  服务监控')
    add_heading(doc, '10.5 缓存监控', level=2)
    add_image(doc, WEB, '33-monitor-cache.png', '图 10-5  缓存监控')
    page_break(doc)

    add_heading(doc, '第 11 章  日志管理', level=1)
    add_heading(doc, '11.1 操作日志', level=2)
    add_image(doc, WEB, '34-log-oper.png', '图 11-1  操作日志')
    add_heading(doc, '11.2 登录日志', level=2)
    add_image(doc, WEB, '35-log-login.png', '图 11-2  登录日志')
    add_heading(doc, '11.3 API 日志', level=2)
    add_image(doc, WEB, '36-log-api.png', '图 11-3  API 日志')
    add_heading(doc, '11.4 AI 服务日志', level=2)
    add_image(doc, WEB, '37-log-ai-service.png', '图 11-4  AI 服务日志')
    add_heading(doc, '11.5 功能点', level=2)
    add_bullet(doc, '操作日志：记录管理员关键操作，含操作人、模块、操作内容、状态。')
    add_bullet(doc, '登录日志：登录成功/失败记录，含 IP、地理位置、浏览器。')
    add_bullet(doc, 'API 日志：接口调用记录，便于排查问题。')
    add_bullet(doc, 'AI 服务日志：AI 规划调用记录，含模型、耗时、Token 消耗。')
    page_break(doc)
