# -*- coding: utf-8 -*-
"""第三册 商户分册（B 端 · Web 商户工作台 /partner）。"""
from manual_lib import *


def build(doc):
    """构建第三册商户分册并写入 doc。"""
    section_title(doc, '第三册')
    section_subtitle(doc, '商户分册 · B 端')
    section_subtitle(doc, 'Web 商户工作台 /partner')
    page_break(doc)

    add_heading(doc, '第 1 章  商户工作台概述', level=1)
    add_para(doc, 'Web 商户工作台（/partner）面向全部 B 端：商户机构、个人服务者、平台运营。提供入驻、接单大厅、报价、卖方订单履约、结算、排期等完整 B 端闭环。商户通过 /login?portal=partner 登录。')
    add_note(doc, '商户工作台账号需先完成入驻审核；演示账号 merchant/merchant123（需 db:seed-merchant 创建）。本手册截图以管理员视角展示。')

    add_heading(doc, '1.1 商户登录入口', level=2)
    add_image(doc, PARTNER, '01-login-partner.png', '图 1-1  Web 商户工作台登录入口')
    add_heading(doc, '1.2 登录流程', level=2)
    add_number(doc, '访问 http://127.0.0.1:5173/login?portal=partner。')
    add_number(doc, '输入商户账号密码，登录后自动跳转 /partner 工作台首页。')
    page_break(doc)

    add_heading(doc, '第 2 章  工作台首页', level=1)
    add_para(doc, '工作台首页展示商户概览：待办需求、进行中订单、待结算金额、近期报价、排期提醒等关键指标。')
    add_image(doc, PARTNER, '02-home.png', '图 2-1  商户工作台首页')
    add_heading(doc, '2.1 功能点', level=2)
    add_bullet(doc, '关键指标卡：待报价、进行中订单、待结算、本月营收。')
    add_bullet(doc, '待办列表：新需求提醒、订单状态变更。')
    add_bullet(doc, '排期提醒：近期服务排期日历。')
    page_break(doc)

    add_heading(doc, '第 3 章  入驻流程', level=1)
    add_para(doc, '新商户通过入驻页提交机构信息、营业执照、团队资质，平台审核通过后正式上线。')
    add_image(doc, PARTNER, '03-onboard.png', '图 3-1  商户入驻页')
    add_heading(doc, '3.1 功能点', level=2)
    add_bullet(doc, '机构信息：名称、类型、联系方式、简介。')
    add_bullet(doc, '资质上传：营业执照、经营许可、团队证书。')
    add_bullet(doc, '服务范围：可接单的目的地、服务类型。')
    add_bullet(doc, '审核状态：待提交 / 审核中 / 已通过 / 已驳回。')
    add_heading(doc, '3.2 操作流程', level=2)
    add_number(doc, '首次登录工作台进入入驻引导。')
    add_number(doc, '填写机构信息并上传资质材料。')
    add_number(doc, '提交后等待平台管理员审核（见第四册机构待审）。')
    add_number(doc, '审核通过后即可在接单大厅报价接单。')
    page_break(doc)

    add_heading(doc, '第 4 章  接单大厅', level=1)
    add_para(doc, '接单大厅聚合平台所有可接单需求，商户按目的地、服务类型、预算筛选并报价。')
    add_image(doc, PARTNER, '04-demands.png', '图 4-1  接单大厅')
    add_heading(doc, '4.1 功能点', level=2)
    add_bullet(doc, '需求卡片：目的地、天数、预算、人数、主题、已报价数。')
    add_bullet(doc, '筛选：目的地、服务类型、预算区间、发布时间。')
    add_bullet(doc, '需求详情：点击进入查看完整需求并报价。')
    add_heading(doc, '4.2 操作流程（报价）', level=2)
    add_number(doc, '在接单大厅筛选合适需求，点击进入详情。')
    add_number(doc, '查看需求细节后点击「报价」。')
    add_number(doc, '填写报价金额、方案摘要、服务承诺。')
    add_number(doc, '提交报价，等待发单方选定（见第二册选定报价流程）。')
    page_break(doc)

    add_heading(doc, '第 5 章  我的报价', level=1)
    add_para(doc, '「我的报价」展示商户提交的全部报价及状态（待选定/已选定/未中标）。')
    add_image(doc, PARTNER, '05-quotes.png', '图 5-1  我的报价')
    add_heading(doc, '5.1 功能点', level=2)
    add_bullet(doc, '报价状态：待发单方选定、已选定（转订单）、未中标。')
    add_bullet(doc, '报价详情：金额、方案、对应需求。')
    add_bullet(doc, '修改/撤回：发单方未选定前可修改或撤回报价。')
    page_break(doc)

    add_heading(doc, '第 6 章  卖方订单管理', level=1)
    add_para(doc, '发单方选定报价后生成服务订单（service_order），商户在订单管理页跟踪履约状态。')
    add_image(doc, PARTNER, '06-orders.png', '图 6-1  卖方订单管理')
    add_heading(doc, '6.1 功能点', level=2)
    add_bullet(doc, '订单状态：待开始、进行中、待验收、已完成、已取消。')
    add_bullet(doc, '履约操作：确认开始、上传履约凭证、提交验收。')
    add_bullet(doc, '订单详情：对应需求、报价、发单方信息、时间线。')
    add_bullet(doc, '与路线解锁订单分表：服务订单独立于路线解锁订单。')
    page_break(doc)

    add_heading(doc, '第 7 章  结算', level=1)
    add_para(doc, '结算页展示商户应收/已结金额、结算单与提现记录。平台按服务订单完成情况结算。')
    add_image(doc, PARTNER, '07-settlements.png', '图 7-1  商户结算')
    add_heading(doc, '7.1 功能点', level=2)
    add_bullet(doc, '结算总览：待结算、已结算、已提现金额。')
    add_bullet(doc, '结算单：按订单生成，含订单号、金额、状态。')
    add_bullet(doc, '提现申请：发起提现至对公账户（生产需对公资质）。')
    page_break(doc)

    add_heading(doc, '第 8 章  排期', level=1)
    add_para(doc, '排期页以日历视图展示商户已接订单的服务时间安排，避免冲突。')
    add_image(doc, PARTNER, '08-schedule.png', '图 8-1  商户排期')
    add_heading(doc, '8.1 功能点', level=2)
    add_bullet(doc, '日历视图：按月/周展示服务排期。')
    add_bullet(doc, '排期冲突检测：新接单时校验时间冲突。')
    add_bullet(doc, '排期详情：点击日程查看对应订单。')
    page_break(doc)
